services:
  afrikaans-reader:
    image: registry.home.lukeboyle.com/afrikaans-reader:${AFRIKAANS_READER_VERSION:-latest}
    container_name: afrikaans-reader
    restart: unless-stopped
    volumes:
      - ${DATA_PATH:-./data}:/app/data
    ports:
      - "${WEB_PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - DATA_DIR=/app/data
